//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyWorkDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_aplicacion
    {
        public int id_aplicacion { get; set; }
        public string cod_aplicacion { get; set; }
        public string nombre_aplicacion { get; set; }
        public string access_id { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public Nullable<bool> gestado { get; set; }
        public Nullable<int> refreshTokenLife { get; set; }
        public string allowedorigin { get; set; }
    }
}
